2024-02-13 21:21:16,887 ERROR: Exception on / [GET] [in C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 947, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'logout' instead?
2024-02-13 21:24:30,894 INFO: Microblog startup [in C:\Users\gushi\Python Projects\social2\app\__init__.py:43]
2024-02-13 21:24:35,313 ERROR: Exception on / [GET] [in C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 947, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'logout' instead?
2024-02-13 21:24:38,977 ERROR: Exception on / [GET] [in C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_login\utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\helpers.py", line 225, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gushi\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\routing\map.py", line 947, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'logout' instead?
